name: nhan_dien_vat_the
description: "Ứng dụng nhận diện vật thể bằng YOLO và TensorFlow Lite."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image: ^4.1.7
  image_picker: ^1.2.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/best.tflite
    - assets/models/labels.txt
    - assets/models/config.json
    - assets/demo/street.jpg
    - assets/demo/room.jpg