/// English keys stay aligned with the model; translations only affect the UI.
const classroomLabels = <String, String>{
  'person': 'Người',
  'cell phone': 'Điện thoại',
  'laptop': 'Laptop',
  'chair': 'Ghế',
  'bottle': 'Chai nước',
  'dining table': 'Bàn (lớp bàn ăn)',
  'tv': 'TV',
  'backpack': 'Ba lô',
  'book': 'Sách',
  'mouse': 'Chuột máy tính',
  'keyboard': 'Bàn phím',
  'remote': 'Điều khiển',
  'clock': 'Đồng hồ',
  'cup': 'Cốc',
  'scissors': 'Kéo',
  'whiteboard': 'Bảng trắng',
  'blackboard': 'Bảng đen',
  'projector': 'Máy chiếu',
  'desk': 'Bàn học',
};

const otherLabels = <String, String>{
  'bus': 'Xe buýt',
  'car': 'Ô tô',
  'truck': 'Xe tải',
  'bicycle': 'Xe đạp',
  'motorcycle': 'Xe máy',
  'airplane': 'Máy bay',
  'train': 'Tàu hỏa',
  'boat': 'Thuyền',
  'traffic light': 'Đèn giao thông',
  'fire hydrant': 'Trụ cứu hỏa',
  'stop sign': 'Biển dừng',
  'parking meter': 'Máy tính phí đỗ xe',
  'bench': 'Ghế dài',
  'bird': 'Chim',
  'cat': 'Mèo',
  'dog': 'Chó',
  'horse': 'Ngựa',
  'sheep': 'Cừu',
  'cow': 'Bò',
  'elephant': 'Voi',
  'bear': 'Gấu',
  'zebra': 'Ngựa vằn',
  'giraffe': 'Hươu cao cổ',
  'umbrella': 'Ô',
  'handbag': 'Túi xách',
  'tie': 'Cà vạt',
  'suitcase': 'Vali',
  'frisbee': 'Đĩa bay',
  'skis': 'Ván trượt tuyết',
  'snowboard': 'Ván tuyết',
  'sports ball': 'Bóng',
  'kite': 'Diều',
  'baseball bat': 'Gậy bóng chày',
  'baseball glove': 'Găng bóng chày',
  'skateboard': 'Ván trượt',
  'surfboard': 'Ván lướt sóng',
  'tennis racket': 'Vợt tennis',
  'wine glass': 'Ly rượu',
  'fork': 'Nĩa',
  'knife': 'Dao',
  'spoon': 'Thìa',
  'bowl': 'Bát',
  'banana': 'Chuối',
  'apple': 'Táo',
  'sandwich': 'Bánh sandwich',
  'orange': 'Cam',
  'broccoli': 'Súp lơ',
  'carrot': 'Cà rốt',
  'hot dog': 'Bánh hot dog',
  'pizza': 'Pizza',
  'donut': 'Bánh donut',
  'cake': 'Bánh ngọt',
  'couch': 'Sofa',
  'potted plant': 'Chậu cây',
  'bed': 'Giường',
  'toilet': 'Bồn cầu',
  'microwave': 'Lò vi sóng',
  'oven': 'Lò nướng',
  'toaster': 'Máy nướng bánh',
  'sink': 'Bồn rửa',
  'refrigerator': 'Tủ lạnh',
  'vase': 'Bình hoa',
  'teddy bear': 'Gấu bông',
  'hair drier': 'Máy sấy tóc',
  'toothbrush': 'Bàn chải đánh răng',
};
String displayLabel(String label) =>
    classroomLabels[label] ?? otherLabels[label] ?? label;
